### ISSUE TITLE
 python-cookbook/src/15/calling_python_from_c/embed.c  cannot compiled by VC++

### ISSUE THREAD

**Issue by Yensan** [dabeaz/python-cookbook#16]
Hi, Dabeaz, I found it is very hard to compile with Visual Studio.
I use this command to compile:

> "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat" amd64 && cl /W4 /EHsc /ZI /MTd /D _UNICODE /Fd:debug/ /Fo:debug/ /IC:/Python3664/include f:\py_c\embed.c /link /LIBPATH:C:/Python3664/libs /out:debug/embed.exe

I have compiled and run it successfully in MacOS with clang.

**Comment by dabeaz** [comment]
It's not likely to work unless compiler options are exactly the same as how Python itself was compiled.  What's the error message?

**Comment by Yensan** [comment]
@dabeaz 
David, I think this is VC++ compiler's bug. Because if I delete all of the `// line comment`, or I just change it into `/* block comments  */`, it can compiled.
Although, I think I should give the compilling command out for other.
Notice: this is just ONE command line, I break it into lines.
>call  "\"C:/Program Files (x86)/Microsoft Visual C++ Build Tools/vcbuildtools.bat\"", "X86",
>                 "&&", "cd", "/d", "${workspaceRoot}", "&&", "cl", "/W4 /EHsc /Ox /GL /DNDEBUG /MT", "-IC:/Python3632/include",
>                 "/Fd:debug/", "/Fo:debug/", "${file}", "/link", "/LIBPATH:C:/Python3632/libs /LIBPATH:C:/Python3632/PCbuild/win32",
>                 "/out:debug/${fileBasenameNoExtension}.exe"

**Comment by Yensan** [comment]
@dabeaz 
I want to ask a question, why you use `distutils` module but not `setuptools` module to generate `setup.py` ? Does any technical consideration? 
And, if I use VC++ to develop *pyd to python64, it is very difficult to compile. Many guys in github and stackOverFlow asked these question. So I Wrote a *bat file to do these things.
usage: two manners to use. I name it `build_pyd.bat`
1.  copy `bat` to `setup.py`, run cmd.exe,  then `call build_pyd.bat`, it will generate a defult python module.
2. if want to sepcify python version, rum cmd.exe, then`call   path/build_pyd.bat  path/to/python.exe  dir/of/setup.py   /rootDir/of/project`

> @echo off && @rem usage: in setup.py dir, "cmd.exe build_pyd"  OR "cmd.exe build_pyd python_path setup.py_dir proj_rootdir"
> @rem if  VC installed, VCbat="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
> @rem Microsoft Visual C++ Build Tools ONLY
> set VCbat="C:\Program Files (x86)\Microsoft Visual C++ Build Tools\vcbuildtools.bat"
> @rem set python path, OR use python in PATH. then Check Python
> if "%1"=="" (set python=python && python -V >nul 2>&1 || (^
>         echo Please setting PATH!!! && set /p DUMMY="Press ENTER key to exit." & exit /b 0)
> ) else (set python=%1 & %1 -V >nul 2>&1 || (echo Invalid python path!!! & exit /b 0))
> @rem set setup.py dir, OR use this bat file dir(bat and py in same dir)
> if "%2"=="" ( set dir=%cd% ) else ( set dir=%2 )
> @rem set logpath, or just use this bat file path
> if "%3"=="" ( set logfile=buildpyd_log.txt ) else ( set logfile="%3/buildpyd_log.txt")
> @rem get Python Version_info, and educe Win32 OR Win64
> for /f "tokens=*" %%i in ('"%python%" -V -V') do set py_v=%%i
> for /f "tokens=1-3 delims=/ " %%1 in ("%date%") do set day=%%1-%%2-%%3
> echo %day% %time% %py_v% && echo %day% %time% %py_v% >> %logfile%
> echo %py_v% | findstr "AMD64" >nul 2>&1 && set platform=amd64 || set platform=X86
> @rem setting MSVC ENV----------
> echo +----- Set VC++ build ENV %platform% && echo +----- Set VC++ build ENV %platform% >> %logfile%
> CALL %VCbat% %platform% >> %logfile% 2>&1
> @rem platform build------------
> echo +----- build pyd && echo +----- build pyd >> %logfile%
> cd /d %dir%
> %python% setup.py build_ext --inplace >> %logfile%
> echo +----- task done
> echo ---------------------- task done -------------------------------- >> %logfile%
> exit /b 0
