### ISSUE TITLE
Some examples don't work

### ISSUE THREAD

**Issue by zwhitchcox** [dabeaz/python-cookbook#6]
This one for instance: mapping_names_to_sequence_elements

**Comment by dabeaz** [comment]
So what's wrong with it specifically?  Do you have a traceback? What version of Python?

**Comment by zwhitchcox** [comment]
I'm not really sure; I'm just now learning python.

```
Traceback (most recent call last):
  File "example1.py", line 5, in <module>
    Stock = namedtuple('Stock' ['name', 'shares', 'price'])
TypeError: string indices must be integers
```

And I tried it with Python 2.7 and 3.42

I'm using a Mac, if that makes a difference.

**Comment by dabeaz** [comment]
You're missing a comma between 'Stock' and the list that follows.    A comma is found in the source code here (at least it looks like there's one to me).

**Comment by zwhitchcox** [comment]
Yep, that fixed it. And using python 3 fixed another one that didn't work. Thank you!

**Comment by dabeaz** [comment]
No problem.  I always appreciate feedback--there's a lot of material in the Cookbook and although I've tried to make it bug free, you never know.  So, I don't mind double checking things.
